version: "3.9"
services:
  meta:
    build: .
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'metadata'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
